### ISSUE TITLE
Support for DevProxy works only in UNIX

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/m365advocacy-templates#10]
The generated project includes some scripts to simulate the ingestion process using Dev Proxy. The scripts are setting a series of environment variables as part of the command, which are needed to define the URL of the proxy and some required Node configuration settings.
This approach, however, works only in Unix-like operating systems. If you try to run the script on Windows, you'll get an error.

**Comment by waldekmastykarz** [comment]
Good catch! That's a typical limitation on Windows, unfortunately. That said, if there's a way to solve it in a x-platform compatible way, it would be awesome. Let's look into it.
