### ISSUE TITLE
Mention the extract() method in the README.md

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/m365advocacy-templates#8]
The README.md file included in the generated project goes through all the features you must implement in the loadContent.js file, but it omits to specify that you must implement the extract() method.
This method is critical because it's used to retrieve the list of external items you want to import from the data source.

**Comment by waldekmastykarz** [comment]
Good catch! It's a typo. In the readme, we mention that in the `loadContent.ts` you should implement the `loadContent` function but that should be `extract`. `loadContent` is good as-is. We'll update it asap. Thanks!
