### ISSUE TITLE
Empty adaptive card in the template

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/m365advocacy-templates#9]
The template includes a definition of an Adaptive Card which is empty. If you don't implement a valid one, you'll get an error when the connection is created.
Make sure to mention this in the README.md and include some guidance on how to build one.

**Comment by waldekmastykarz** [comment]
Good catch! I was convinced we had instructions on it, but it seems like they're missing from the readme. We'll add them asap. Thanks!
